controllers:
    resource: ../src/Controller/
    type: attribute


index: 
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::numberAction

blog_list:
    path:     /blog
    controller: App\Controller\BlogController::list

blog_show:
    path:     /blog/{entryId}
    controller: App\Controller\BlogController::show